"0104":
  name: Elizabeth Ann Seton
  rank: OPTIONAL
  collect: >
    Give us grace, O God, to love you in all things and
    above all things; that, following the example of your
    servant Elizabeth Ann Seton, we might express our love
    for you in the service of others. Through Jesus Christ
    our Lord, who lives and reigns with you and the Holy
    Spirit, one God, in glory everlasting. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0105":
  name: Sarah, Theodora, and Syncletica of Egypt
  rank: OPTIONAL
  collect: >
    Fix our hearts on You, O God, in pure devotion, that
    aided by the example of your servants Sarah, Theodora,
    and Syncletica, the vain pursuits of this world may have
    no hold upon us, and that by the consuming fire of your
    Spirit, we may be changed into the image and likeness of
    your Son, Jesus Christ our Lord; to whom with you and
    the same Spirit be all honor and glory, now and for ever.
    Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0114":
  name: Richard Meux Benson
  rank: OPTIONAL
  collect: >
    Gracious God, who kindled in your servants Richard
    Meux Benson and Charles Gore the grace to lead
    a revival of monastic life: Grant us also the resolve
    to serve you faithfully in contemplation and prayer,
    ministering to the world that you have made, through
    Jesus Christ our Lord, who lives and reigns with you
    and the Holy Spirit, ever one God, in glory everlasting.
    Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0131":
  name: Marcella of Rome
  rank: OPTIONAL
  collect: >
    O God, who satisfies the longing soul and fills the
    hungry with good things: Grant that we, like your
    servant Marcella, may hunger and thirst after you above
    the vain pomp and glory of the world, and delight in
    your word above all manner of riches; through Jesus
    Christ our Lord, who lives and reigns with you and the
    Holy Spirit, one God, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0206":
  name: The Martyrs of Japan 1597
  rank: OPTIONAL
  collect: >
    O God our Father, who brought the holy martyrs of
    Japan through the suffering of the cross to the joys of
    eternal life: Grant that we, encouraged by their example,
    may hold fast to the faith we profess, even unto death
    itself; through Jesus Christ our Lord, who lives and
    reigns with you and the Holy Spirit, one God, now and
    for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0208":
  name: Bakhita (Josephine Margaret Bakhita)
  rank: OPTIONAL
  collect: >
    O God of Love, who delivered your servant Josephine
    Margaret Bakhita from the bondage of slavery to the
    true freedom of your service; Grant to the wounded
    your healing grace in mind, body, and spirit and to your
    church the zeal to combat exploitation and slavery in all
    its forms; through Jesus Christ our Lord. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0210":
  name: Scholastica of Nursia
  rank: OPTIONAL
  collect: >
    Assist us, O God, to love one another as sisters and
    brothers, and to balance discipline with love and rules
    with compassion, according to the example shown by
    your servant Scholastica; for the sake of your Son Jesus
    Christ our Lord, to whom with you and the Holy Spirit
    be all honor and glory, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0211":
  name: The Consecration of Barbara Clementine Harris
  rank: OPTIONAL
  collect: >
    God of the prophets, we give you thanks for calling
    Barbara Clementine Harris to the office of bishop.
    Open our eyes to behold the wondrous works you have
    prepared for your church in calling women to share in
    the ministry of the episcopate. May we, inspired by their
    example as faithful shepherds, wise teachers, courageous
    prophets, and guardians of the faith, proclaim the Good
    News and carry out the works of Jesus Christ in the
    world; who with you and the Holy Spirit lives and reigns
    for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0212":
  name: Theodora
  rank: OPTIONAL
  collect: >
    O God, who called your servant Theodora to an earthly
    throne that she might advance your heavenly kingdom
    and who gave her the wisdom to establish unity where
    there had been division; Create in your church such
    godly union and concord that we might proclaim
    the Gospel of the Prince of Peace, not only in correct
    theology but in right actions; through the same Jesus
    Christ our Lord, who lives and reigns with you and the
    Holy Spirit, one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0219":
  name: Agnes Tsao Kou Ying, Agatha Lin Zhao, and Lucy Yi Zhenmei
  rank: OPTIONAL
  collect: >
    Lord Jesus Christ, who willingly walked the way of
    the cross: Strengthen your church through the witness
    of your servants Agnes Tsao Kou Ying, Agatha Lin
    Zhao, and Lucy Yi Zhenmei to hold fast to the path of
    discipleship even unto death; for with the Father and
    Holy Spirit you live and reign, one God, for ever and
    ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0220":
  name: Frederick Douglass
  rank: OPTIONAL
  collect: >
    Almighty God, we bless your Name for the witness of
    Frederick Douglass, whose impassioned and reasonable
    speech moved the hearts of people to a deeper obedience
    to Christ: Strengthen us also to speak on behalf of those
    in captivity and tribulation, continuing in the way of
    Jesus Christ our Liberator; who with you and the Holy
    Spirit dwells in glory everlasting. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0222":
  name: Margaret of Cortona
  rank: OPTIONAL
  collect: >
    Grant, O God, to all your people, as to your servant
    Margaret of Cortona, the spirit of repentance and
    supplication, that we might seek and desire nothing in
    this transitory life above you; through Jesus Christ our
    Lord. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0225":
  name: Emily Malbone Morgan
  rank: OPTIONAL
  collect: >
    Inspire us, Gracious God, with that same spirit of
    devotion that animated your servant Emily Malbone
    Morgan; that, like her, we might dedicate our lives to
    your service and to the welfare of others; through Jesus
    Christ our Lord, who lives and reigns with you, in the
    unity of the Holy Spirit, one God, now and for ever.
    Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0226":
  name: Photini The Samaritan Woman, c. 67
  rank: OPTIONAL
  collect: >
    O Almighty God, whose most blessed Son revealed to
    the Samaritan woman that He is indeed the Christ, the
    Savior of the World; Grant us to drink of the well that
    springs up to everlasting life that we may worship you
    in spirit and in truth through your Son, Jesus Christ our
    Lord. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0301":
  name: David of Wales
  rank: OPTIONAL
  collect: >
    Almighty God, who called your servant David to be
    a faithful and wise steward of your mysteries for the
    people of Wales: Mercifully grant that, following his
    purity of life and zeal for the Gospel of Christ, we may,
    with him, praise you both here on earth and also in
    your everlasting kingdom; through Jesus Christ our
    Lord, who lives and reigns with you and the Holy Spirit,
    one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0302":
  name: Chad of Lichfield
  rank: OPTIONAL
  collect: >
    Heavenly Father, whose son our Lord Jesus Christ took
    the form of a servant for the sake of his brothers and
    sisters: Strengthen us with the prayers and example
    of your servant Chad, who became the least of all to
    minister to all; through the same Christ our Lord, who
    lives and reigns, with you and the Holy Spirit, one God,
    now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0303":
  name: John and Charles Wesley
  rank: OPTIONAL
  collect: >
    Lord God, you inspired your servants John and Charles
    Wesley with burning zeal for the sanctification of souls
    and endowed them with eloquence in speech and song:
    Kindle such fervor in your church, we entreat you, that
    those whose faith has cooled may be warmed, and
    those who have not known Christ may turn to him and
    be saved; who lives and reigns with you and the Holy
    Spirit, one God, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0307":
  name: Perpetua and Felicity
  rank: OPTIONAL
  collect: >
    O God, the King of Saints, who strengthened your
    servants Perpetua, Felicity, and their companions to
    make a good confession and to encourage one another
    in the time of trial: Grant that we who cherish their
    blessed memory may share their pure and steadfast
    faith, and win with them the palm of victory; through
    Jesus Christ our Lord, who lives and reigns with you
    and the Holy Spirit, one God, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0309":
  name: Gregory of Nyssa
  rank: OPTIONAL
  collect: >
    Almighty God, who has revealed to your Church your
    eternal Being of glorious majesty and perfect love as one
    God in Trinity of Persons: Give us grace that, like your
    bishop Gregory of Nyssa, we may continue steadfast in
    the confession of this faith, and constant in our worship
    of you, Father, Son and Holy Spirit; who live and reign
    for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0310":
  name: Harriet Ross Tubman
  rank: OPTIONAL
  collect: >
    O God, whose Spirit guides us into all truth and
    makes us free: Strengthen and sustain us as you did
    your servant Harriet Ross Tubman. Give us vision and
    courage to stand against oppression and injustice and all
    that works against the glorious liberty to which you call
    all your children; through Jesus Christ our Savior, who
    lives and reigns with you and the Holy Spirit, one God,
    for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0312":
  name: Gregory the Great
  rank: OPTIONAL
  collect: >
    Almighty and merciful God, you raised up Gregory
    of Rome to be a servant of the servants of God, and
    inspired him to send missionaries to preach the Gospel
    to the English people: Preserve your church in the
    catholic and apostolic faith, that your people, being
    fruitful in every good work, may receive the crown of
    glory that never fades away; through Jesus Christ our
    Lord, who lives and reigns with you and the Holy Spirit,
    one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0313":
  name: James Theodore Holly
  rank: OPTIONAL
  collect: >
    Most gracious God, whose servant James Theodore
    Holly labored to build a church in which all might be
    free: Grant that we might overcome our prejudice, and
    honor those whom you call from every family, language,
    people, and nation; through Jesus Christ our Lord, who
    lives and reigns with you and the Holy Spirit, one God,
    now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0315":
  name: Vincent de Paul
  rank: OPTIONAL
  collect: >
    Most Gracious God, who has bidden us to act justly,
    love mercy, and walk humbly before you; Teach us, like
    your servants Vincent de Paul and Louise de Marillac,
    to see and to serve Christ by feeding the hungry,
    welcoming the stranger, clothing the naked, and caring
    for the sick; that we may know him to be the giver of all
    good things, through the same Jesus Christ our Lord.
    Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0317":
  name: Patrick of Ireland
  rank: OPTIONAL
  collect: >
    Almighty God, in your providence you chose your
    servant Patrick to be the apostle to the Irish people, to
    bring those who were wandering in darkness and error
    to the true light and knowledge of you: Grant us so to
    walk in that way that we may come at last to the light of
    everlasting life; through Jesus Christ our Lord, who lives
    and reigns with you and the Holy Spirit, one God, for
    ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0318":
  name: Cyril of Jerusalem
  rank: OPTIONAL
  collect: >
    Strengthen, O God, your church in the sacraments of
    your grace, that we, in union with the teaching and
    prayers of your servant Cyril of Jerusalem, may enter
    more fully into your Paschal mystery; through Jesus
    Christ our Lord, who lives and reigns with you and the
    Holy Spirit, one God, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0320":
  name: Cuthbert
  rank: OPTIONAL
  collect: >
    Merciful God, who called Cuthbert from following
    the flock to be a shepherd of your people: Mercifully
    grant that we also may go without fear to dangerous
    and remote places, to seek the indifferent and the lost;
    through Jesus Christ our Lord, who lives and reigns
    with you and the Holy Spirit, one God, for ever and
    ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0321":
  name: Thomas Ken
  rank: OPTIONAL
  collect: >
    Almighty God, you gave your servant Thomas Ken
    grace and courage to bear witness to the truth before
    rulers and kings: Give us strength also that we may
    constantly defend what is right, boldly reprove what is
    evil, and patiently suffer for the truth's sake; through
    Jesus Christ our Lord, who lives and reigns with you
    and the Holy Spirit, one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0322":
  name: James De Koven
  rank: OPTIONAL
  collect: >
    Almighty and everlasting God, who led your servant
    James De Koven to honor your presence at the altar, and
    constantly to point to Christ: Grant that all ministers
    and stewards of your mysteries may impart to your
    faithful people the knowledge of your presence and the
    truth of your grace; through the same Jesus Christ our
    Lord, who lives and reigns with you and the Holy Spirit,
    one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0323":
  name: Gregory the Illuminator
  rank: OPTIONAL
  collect: >
    Almighty God, who raised up your servant Gregory to
    be a light in the world, and to preach the Gospel to the
    people of Armenia: Illuminate our hearts, that we also
    in our own generation may show forth your praise, who
    called us out of darkness and into your marvelous light;
    through Jesus Christ our Lord, who lives and reigns
    with you and the Holy Spirit, one God, now and for
    ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0324":
  name: Óscar Romero
  rank: OPTIONAL
  collect: >
    Almighty God, you called your servant Óscar Romero
    to be a voice for the voiceless poor, and to give his life
    as a seed of freedom and a sign of hope: Grant that we,
    inspired by his sacrifice and the example of the martyrs
    of El Salvador, may without fear or favor witness to
    your Word who abides, your Word who is Life, even
    Jesus Christ our Lord, to whom, with you and the Holy
    Spirit, be praise and glory now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0326":
  name: Harriet Monsell
  rank: OPTIONAL
  collect: >
    Gracious God, who led your servant Harriet Monsell
    through grief to a new vocation; grant that we, inspired
    by her example, may grow in the life of prayer and the
    work of service so that in sorrow or joy, your presence
    may increase among us and our lives reveal the mind of
    Jesus Christ, to whom, with you and the Holy Spirit be
    honor and glory, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0327":
  name: Charles Henry Brent
  rank: OPTIONAL
  collect: >
    Heavenly Father, whose Son prayed that we all might be
    one: Deliver us from arrogance and prejudice, and give
    us wisdom and forbearance, that, following your servant
    Charles Henry Brent, we may be united in one family
    with all who confess the Name of your Son Jesus Christ;
    who lives and reigns with you and the Holy Spirit, one
    God, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0328":
  name: James Solomon Russell
  rank: OPTIONAL
  collect: >
    O God, the font of resurrected life, draw us into the
    wilderness and speak tenderly to us, so that we might
    love and worship you as your servant James Solomon
    Russell did, in assurance of the saving grace of Jesus
    Christ, who lives and reigns with you and the Holy
    Spirit, one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0329":
  name: John Keble
  rank: OPTIONAL
  collect: >
    Grant, O God, that in all time of our testing we may
    know your presence and obey your will, that, following
    the example of your servant John Keble, we may
    accomplish with integrity and courage what you give
    us to do and endure what you give us to bear; through
    Jesus Christ our Lord, who lives and reigns with you
    and the Holy Spirit, one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0330":
  name: Mary of Egypt
  rank: OPTIONAL
  collect: >
    Merciful Lord, who raises up sinners by your boundless
    compassion and mercy: Cause the desert sun to burn
    away our coarseness and to melt our hardness of heart,
    that, like your servant Mary of Egypt, we may not
    depart from this life until we understand the ways of
    repentance and the benefits of prayer; through Jesus
    Christ our Lord, who lives and reigns with you and the
    Holy Spirit, one God, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0331":
  name: John Donne
  rank: OPTIONAL
  collect: >
    O God of eternal glory, whom no one living can see and
    yet whom to see is to live; grant that with your servant
    John Donne, we may see your glory in the face of your
    Son, Jesus Christ, and then, with all our skill and wit,
    offer you our crown of prayer and praise, until by his
    grace we stand in that last and everlasting day, when
    death itself will die, and all will live in you, who with
    the Holy Spirit and the same Lord Jesus Christ are one
    God in everlasting light and glory. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0401":
  name: Frederick Denison Maurice
  rank: OPTIONAL
  collect: >
    Almighty God, who has restored our human nature to
    heavenly glory through the perfect obedience of our
    Savior Jesus Christ: Enliven in your Church, we pray,
    the passion for justice and truth, that, like your servant
    Frederick Denison Maurice, we may work and pray for
    the triumph of the kingdom of Christ; who lives and
    reigns with you and the Holy Spirit, one God, now and
    for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0402":
  name: James Lloyd Breck
  rank: OPTIONAL
  collect: >
    O God, who sent your Son to preach peace to those
    who are far off and to those who are near: call us from
    comfortable complacency to preach, teach, and plant
    your church on new frontiers, after the example of your
    servant James Lloyd Breck; through Jesus Christ our
    Lord, who lives and reigns with you and the Holy Spirit,
    one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0403":
  name: Richard of Chichester
  rank: OPTIONAL
  collect: >
    Almighty and most merciful God, who calls your people
    to yourself, we pray that, following the example of your
    bishop Richard of Chichester, we may see your Son
    Jesus Christ more clearly, love him more dearly, and
    follow him more nearly; who lives and reigns with you
    and the Holy Spirit, one God, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0404":
  name: Martin Luther King, Jr. Pastor and Martyr
  rank: OPTIONAL
  collect: >
    Almighty God, by the hand of Moses your servant you
    led your people out of slavery, and made them free at
    last: Grant that your church, following the example of
    your prophet Martin Luther King, may resist oppression
    in the name of your love, and may strive to secure for all
    your children the blessed liberty of the Gospel of Jesus
    Christ; who lives and reigns with you and the Holy
    Spirit, one God, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0405":
  name: Harriet Starr Cannon
  rank: OPTIONAL
  collect: >
    Gracious God, who called Harriet Starr Cannon and
    her companions to revive the monastic vocation in the
    Episcopal Church and to dedicate their lives to you:
    Grant that we, after their example, may ever surrender
    ourselves to the revelation of your holy will; through our
    Lord and Savior Jesus Christ, who lives and reigns with
    you and the Holy Spirit, one God, for ever and ever.
    Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0407":
  name: Tikhon
  rank: OPTIONAL
  collect: >
    Holy God, holy and mighty, you call us together into
    one communion and fellowship: Open our eyes, we
    pray, as you opened the eyes of your servant Tikhon,
    that we may see the faithfulness of others as we strive to
    be steadfast in the faith delivered unto us, that the world
    may see and know you; through Jesus Christ our Lord,
    to whom, with you and the Holy Spirit, be glory and
    praise unto ages of ages. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0408":
  name: William Augustus Muhlenberg
  rank: OPTIONAL
  collect: >
    Open the eyes of your church, O Lord, to the plight of
    the poor and neglected, the homeless and destitute, the
    old and the sick, the lonely and those who have none
    to care for them. Give to us the vision and compassion
    with which you so richly endowed your servant William
    Augustus Muhlenberg, that we may labor tirelessly to
    heal those who are broken in body or spirit, and to turn
    their sorrow into joy; through Jesus Christ our Lord,
    who lives and reigns with you and the Holy Spirit, one
    God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0409":
  name: Dietrich Bonhoeffer
  rank: OPTIONAL
  collect: >
    Embolden our lives, O Lord, and inspire our faiths,
    that we, following the example of your servant Dietrich
    Bonhoeffer, might embrace your call with undivided
    hearts; through Jesus Christ our Savior, who lives and
    reigns with you and the Holy Spirit, one God, for ever
    and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0410":
  name: William Law
  rank: OPTIONAL
  collect: >
    Almighty God, whose servant William Law taught us
    to hear and follow your call to a devout and holy life:
    Grant that we, loving you above all things and in all
    things, may seek your purpose and shape our actions to
    your will, that we may grow in all virtue and be diligent
    in prayer all the days of our lives, through Jesus Christ
    our Lord, to whom with you and the Holy Spirit be all
    honor and glory now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0411":
  name: George Augustus Selwyn
  rank: OPTIONAL
  collect: >
    Almighty and everlasting God, whose servant George
    Augustus Selwyn laid a firm foundation for the growth
    of your church in many nations: Raise up in this and
    every land evangelists and heralds of your kingdom,
    that your church may proclaim the unsearchable riches
    of our Lord Jesus Christ; who lives and reigns with you
    and the Holy Spirit, one God, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0414":
  name: Zenaida, Philonella, and Hermione
  rank: OPTIONAL
  collect: >
    Merciful God, whose most dear Son came to heal the
    sick, raise the dead, cast out demons, and preach good
    news to the poor: Lead us by the example of your
    servants, Zenaida, Philonella, and Hermione, to freely
    give even as we have freely received; through Jesus
    Christ our Lord. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0415":
  name: Damien
  rank: OPTIONAL
  collect: >
    Bind up the wounds of your children, O God, and
    help us to be bold and loving in service to all who are
    shunned for the diseases they suffer, following the
    example of your servants Damien and Marianne, that
    your grace may be poured forth upon all; through Jesus
    Christ our Lord, who with you and the Holy Spirit lives
    and reigns, one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0416":
  name: Peter Williams Cassey
  rank: OPTIONAL
  collect: >
    O God of justice and mercy, we remember before you
    your servants Peter Williams Cassey and Anna Besant
    Cassey, who, in the face of slavery and discrimination,
    gave the blessings of education and spiritual haven to
    the marginalized; Grant us to be fearless in the face of
    injustice and to work for blessings that will touch those
    whom the world does not count of value; through Jesus
    Christ our Lord, who with you and the Holy Spirit lives
    and reigns for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0417":
  name: Kateri Tekakwitha
  rank: OPTIONAL
  collect: >
    Almighty and everliving God, who opened the heart of
    Kateri Tekakwitha to receive the Good News of Jesus
    Christ and to devote her life to your service: Grant us
    the same zeal of devotion to persevere in faith through
    the trials and tribulations of our lives, through Jesus
    Christ our Lord. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0418":
  name: Juana Inés de la Cruz
  rank: OPTIONAL
  collect: >
    Almighty God, Source of all knowledge, we give you
    thanks for the witness of your servant Juana Inés de la
    Cruz in her fierce passion for learning and creativity.
    Teach us to be faithful stewards of our minds and
    hearts, so that, following her example, we might forever
    proclaim the riches of your unending love in Jesus
    Christ our Lord. Through Jesus Christ who, with you
    and the Holy Spirit, lives and reigns, one God, for ever
    and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0419":
  name: Alphege
  rank: OPTIONAL
  collect: >
    Lord Jesus Christ, who willingly walked the way of the
    cross: Strengthen your church through the example and
    prayers of your servant Alphege to hold fast to the path
    of discipleship; for with the Father and Holy Spirit you
    live and reign, one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0421":
  name: Anselm of Canterbury
  rank: OPTIONAL
  collect: >
    Almighty God, whose servant Anselm helped your
    church to understand its faith in your eternal Being,
    perfect justice, and saving mercy: Provide your church in
    all ages with devout and learned scholars and teachers,
    that we may be able to give a reason for the hope that
    is in us; through Jesus Christ our Lord, who lives and
    reigns with you and the Holy Spirit, one God, for ever
    and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0422":
  name: Hadewijch of Brabant
  rank: OPTIONAL
  collect: >
    Triune God of Love, overwhelming and all-
    encompassing: Visit us in our solitude and in our
    companionship, and draw us ever more deeply
    into union with you, who are ever present and ever
    mysterious; that we, like your servant Hadewijch, might
    know you ever more fully, even as we have been fully
    known. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0423":
  name: Toyohiko Kagawa
  rank: OPTIONAL
  collect: >
    Strengthen and protect, O God, all those who suffer
    for their fidelity to Jesus Christ; that, like your servant
    Toyohiko Kagawa, they might persevere in seeking and
    serving Christ in all persons, and work tirelessly for the
    advancement of your kingdom; through the same Jesus
    Christ our Lord, to whom with you and the Holy Spirit
    be all honor and glory now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0427":
  name: Zita of Tuscany
  rank: OPTIONAL
  collect: >
    Merciful God, who has given to us all things necessary
    for life and godliness; Grant that we, like your servant
    Zita, may be faithful in the exercise of our duties and
    that, whatever you give us to do, we may do it heartily
    to you for the honor and glory of your Name; through
    him who has called us to virtue, Jesus Christ, your Son,
    our Lord. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0429":
  name: Catherine of Siena
  rank: OPTIONAL
  collect: >
    Almighty and everlasting God, who kindled the flame
    of your love in the heart of your servant Catherine of
    Siena: Grant unto us the same strength of conviction
    and power of love that, as we rejoice in her triumph,
    we may profit by her example; through Jesus Christ our
    Lord. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0503":
  name: Elisabeth Cruciger
  rank: OPTIONAL
  collect: >
    Pour out your Spirit upon all of your sons and
    daughters, Almighty God, that like your servant
    Elisabeth Cruciger our lips may praise you, our lives
    may bless you, and our worship may give you glory;
    through Jesus Christ our Lord. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0505":
  name: Martyrs of the Reformation Era
  rank: OPTIONAL
  collect: >
    Almighty and Most Merciful God, give to your church
    that peace which the world cannot give, and grant that
    those who have been divided on earth may be reconciled
    in heaven, and share together in the vision of your glory;
    through Jesus Christ your Son our Lord, who lives and
    reigns with you, in the unity of the Holy Spirit, one
    God, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0511":
  name: Johann Arndt and Jacob Boehme
  rank: OPTIONAL
  collect: >
    Holy God, who dwells with those who have a contrite
    and humble spirit: Revive our spirits; purify us from
    deceitful lusts; and clothe us in righteousness and true
    holiness; though Jesus Christ our Lord, who lives and
    reigns with you and the Holy Spirit, one God now and
    for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0513":
  name: Frances Perkins
  rank: OPTIONAL
  collect: >
    Loving God, we bless your Name for Frances Perkins,
    who in faithfulness to her baptism envisioned a society
    in which all might live in health and decency: Help us,
    following her example and in union with her prayers, to
    contend tirelessly for justice and for the protection of all,
    that we may be faithful followers of Jesus Christ; who
    with you and the Holy Spirit lives and reigns, one God,
    for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0515":
  name: Pachomius of Tabenissi
  rank: OPTIONAL
  collect: >
    Set us free, O God, from all false desires, vain
    ambitions, and everything that would separate us from
    your love; that, like your servant Pachomius, we might
    give ourselves fully to a life of discipleship, seeking
    you alone and serving those whom you have given us
    to serve; through Jesus Christ, our only mediator and
    advocate. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0517":
  name: Thurgood Marshall
  rank: OPTIONAL
  collect: >
    Eternal and ever-gracious God, who blessed your
    servant Thurgood Marshall with grace and courage to
    discern and speak the truth: Grant that, following his
    example, we may know you and recognize that we are
    all your children, brothers and sisters of Jesus Christ,
    who lives and reigns with you and the Holy Spirit, one
    God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0521":
  name: Lydia of Thyatira
  rank: OPTIONAL
  collect: >
    Eternal God, who gives good gifts to all people, and
    who grants the spirit of generosity: Give us, we pray
    you, hearts always open to hear your word, that,
    following the example of your servant Lydia, we may
    show hospitality to those who are in any need or
    trouble; through Jesus Christ our Lord who lives and
    reigns with you and the Holy Spirit, one God, now and
    for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0522":
  name: Helena of Constantinople
  rank: OPTIONAL
  collect: >
    Most Merciful God, who blessed your servant Helena
    with such grace and devotion to you that she venerated
    the very footsteps of our Savior; Grant unto us the same
    grace that, aided by her prayers and example, we also
    may always behold your glory in the cross of your Son.
    Through the same Jesus Christ our Lord; who lives and
    reigns with you, in the unity of the Holy Spirit, one
    God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0528":
  name: Mechthild of Magdeburg
  rank: OPTIONAL
  collect: >
    Draw the souls of your people into your love, O God,
    that like your servant Mechthild, we may yearn to be
    fully yours, for you know us better than we can know
    ourselves; through Jesus Christ our Lord, who lives and
    reigns with you and the Holy Spirit, one God now and
    for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0604":
  name: John XXIII (Angelo Giuseppe Roncalli)
  rank: OPTIONAL
  collect: >
    God of all truth and peace, who raised up your bishop
    John to be servant of the servants of God and bestowed
    on him wisdom to call for the work of renewing your
    church: Grant that, following his example, we may
    reach out to other Christians in the love of your Son,
    and labor throughout the nations of the world to kindle
    a desire for justice and peace; through Jesus Christ our
    Lord, who lives and reigns with you and the Holy Spirit,
    one God, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0608":
  name: Melania the Elder
  rank: OPTIONAL
  collect: >
    Most High and Merciful God, who called your servant
    Melania to forsake earthly comforts in order to devote
    herself to studying the scriptures and to welcoming the
    poor: Instruct us in the ways of poverty and the grace
    of hospitality, that we might comfort those who have
    no place to rest and teach the way of your love; through
    Jesus Christ our Lord. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0613":
  name: The First Book of Common Prayer
  rank: OPTIONAL
  collect: >
    Almighty and everliving God, who through the Book
    of Common Prayer restored the language of the people
    in the prayers of your church: Make us always thankful
    for this heritage; and help us so to pray in the Spirit and
    with understanding, that we may worthily magnify your
    holy Name; through Jesus Christ our Lord, who lives
    and reigns with you and the Holy Spirit, one God, for
    ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0617":
  name: Marina the Monk Monastic, fifth century
  rank: OPTIONAL
  collect: >
    Give us grace, Lord God, to refrain from judgments
    about the sins of others; that, like your servant Marina
    the Monk, we may hold fast to the path of discipleship
    in the midst of unjust judgments; through Jesus Christ
    our Lord who lives and reigns with you and the Holy
    Spirit, one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0626":
  name: Isabel Florence Hapgood
  rank: OPTIONAL
  collect: >
    Teach your divided church, O God, so to follow the
    example of your servant Isabel Florence Hapgood that
    we might look upon one another with a holy envy,
    to honor whatever is good and right in our separate
    traditions, and to continually seek the unity that you
    desire for all your people. We ask this in the name of
    Jesus Christ our Lord, who prayed that his church might
    be one. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0701":
  name: Pauli Murray
  rank: OPTIONAL
  collect: >
    Liberating God, we thank you for the steadfast courage
    of your servant Pauli Murray, who fought long and
    well: Unshackle us from the chains of prejudice and
    fear, that we may show forth the reconciling love and
    true freedom which you revealed in your Son our Savior
    Jesus Christ; who lives and reigns with you and the Holy
    Spirit, one God, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0702":
  name: Moses the Black
  rank: OPTIONAL
  collect: >
    Almighty God, whose blessed Son guides our footsteps
    in the way of peace: Deliver us from the paths of hatred
    and violence, that we, following the example of your
    servant Moses, may serve you with singleness of heart
    and attain to the tranquility of the world to come;
    through Jesus Christ our Lord, who lives and reigns
    with you in the unity of the Holy Spirit, one God, now
    and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0706":
  name: Eva Lee Matthews
  rank: OPTIONAL
  collect: >
    O God, whose blessed Son became poor that we
    through his poverty might be rich: Deliver us from
    an inordinate love of this world, that, inspired by the
    devotion of your servant Eva Lee Matthews, we may
    serve you with singleness of heart, and attain to the
    riches of the age to come; through the same Jesus Christ
    our Lord, who lives and reigns with you, in the unity of
    the Holy Spirit, one God, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0708":
  name: Priscilla and Aquila
  rank: OPTIONAL
  collect: >
    God of grace and might, who gave to your servants
    Aquila and Priscilla gifts of zeal and eloquence to make
    known the truth of the Gospel: Raise up, we pray, in
    every country, heralds and evangelists of your kingdom,
    so that the world may know the immeasurable riches of
    our Savior Jesus Christ; who lives and reigns with you
    and the Holy Spirit, one God, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0714":
  name: Argula von Grumbach
  rank: OPTIONAL
  collect: >
    Almighty God, who gave your servant Argula von
    Grumbach a spirit of wisdom and power to love your
    Word and to boldly draw others to its truth: Pour out
    that same spirit upon us, that we, knowing and loving
    your Holy Word, may be unashamed of Christ and may
    not sin against the Holy Spirit that is within us. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0721":
  name: Maria Skobtsova
  rank: OPTIONAL
  collect: >
    O Creator and Giver of Life, who crowned your
    martyr Maria Skobtsova with glory and gave her as an
    example of service to the suffering and poor even unto
    death: Teach us to love Christ in our neighbors, and
    thereby battle injustice and evil with the light of the
    Resurrection; through Jesus Christ our Lord, who lives
    and reigns with you and the Holy Spirit, one God in
    glory everlasting. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0723":
  name: John Cassian
  rank: OPTIONAL
  collect: >
    Holy God, whose beloved Son Jesus Christ blessed the
    pure in heart: Grant that we, together with your servant
    John Cassian and in union with his prayers, may ever
    seek the purity with which to behold you as you are; one
    God in Trinity of persons now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0728":
  name: Johann Sebastian Bach
  rank: OPTIONAL
  collect: >
    Sound out your majesty, O God, and call us to your
    work; that, like thy servant Johann Sebastian Bach, we
    might present our lives and our works to your glory
    alone; through Jesus Christ our Lord, who lives and
    reigns with you and the Holy Spirit, one God, for ever
    and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0803":
  name: Joanna, Mary, and Salome Myrrh-Bearing Women
  rank: OPTIONAL
  collect: >
    Almighty God, who revealed the resurrection of your
    Son to Joanna, Mary, and Salome as they faithfully
    came bearing myrrh to his tomb: Grant that we too may
    perceive the presence of the risen Lord in the midst of
    pain and fear, and go forth proclaiming his resurrection;
    who lives and reigns with you and the Holy Spirit, one
    God, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0809":
  name: Edith Stein (Teresa Benedicta of the Cross)
  rank: OPTIONAL
  collect: >
    Pour out your grace upon thy church, O God; that,
    like your servant Edith Stein, we may always seek what
    is true, defend what is right, reprove what is evil, and
    forgive those who sin against us, even as your Son
    commanded; through the same Jesus Christ our Lord,
    to whom with you and the Holy Spirit be all honor and
    glory, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0826":
  name: Simeon Bachos, the Ethiopian Eunuch
  rank: OPTIONAL
  collect: >
    Holy One of love, you called your servant Simeon
    Bachos to study your word and led him to the waters of
    baptism, making him your evangelist to Ethiopia: give
    us the grace to follow where you lead, overcoming the
    barriers that divide and diminish your people, that we
    may behold you in all your glory; through our Savior
    and Lord Jesus Christ, who with you and the Holy Spirit
    lives and reign for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0829":
  name: The Beheading of Saint John the Baptist
  rank: OPTIONAL
  collect: >
    Almighty God, who called your servant John the Baptist
    to go before your Son our Lord both in life and death;
    Grant that we who remember his witness may with
    boldness speak your truth and in humility hear it when
    it is spoken to us, through Jesus Christ, the firstborn
    from the dead, who with you and the Holy Spirit lives
    and reigns one God for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0830":
  name: Margaret Ward, Margaret Clitherow, and Anne Line
  rank: OPTIONAL
  collect: >
    Most Merciful God, who despises not a broken and
    contrite heart and has promised to fill those who hunger
    and thirst after righteousness; We humbly beseech you,
    remember not the sins and offenses of our ancestors, but
    grant that, like your servants Margaret Ward, Margaret
    Clitherow, and Anne Line, we may sanctify you in our
    hearts and be always ready to answer for our faith with
    meekness and fear; through our only Mediator and
    Advocate, Jesus Christ our Lord. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0903":
  name: Phoebe
  rank: OPTIONAL
  collect: >
    Eternal God, who raised up Phoebe as a deacon in your
    church and minister of your Gospel; Grant us that same
    grace that, assisted by her prayers and example, we too
    may take the Gospel to the ends of the earth; through
    Jesus Christ your Son our Lord who lives and reigns
    with you, in the unity of the Holy Spirit, one God, for
    ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0905":
  name: Katharina Zell
  rank: OPTIONAL
  collect: >
    Almighty God, whose servant Katharina Zell toiled for
    the reform of your church both in word and in deed:
    Fill us with the wisdom to speak out in defense of your
    truth, with love for you and for our neighbor, that we
    may serve you and welcome all your people with a
    mother's heart; through Christ our Lord. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0906":
  name: Hannah More
  rank: OPTIONAL
  collect: >
    Almighty God, whose only-begotten Son led captivity
    captive: Multiply among us faithful witnesses like your
    servant Hannah More, who will fight for all who are
    oppressed or held in bondage, and bring us all, we pray,
    into the glorious liberty that you have promised to all
    your children; through Jesus Christ our Lord, who lives
    and reigns with you and the Holy Spirit, one God, for
    ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0907":
  name: Kassiani
  rank: OPTIONAL
  collect: >
    O God of boundless mercy, whose handmaiden Kassiani
    brought forth poetry and song: Inspire in your church a
    new song, that following her most excellent example, we
    may boldly proclaim the truth of your Word; even Jesus
    Christ, our Savior and Deliverer. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0908":
  name: The Nativity of the Virgin Mary
  rank: OPTIONAL
  collect: >
    Father in heaven, by your grace the virgin mother of
    your incarnate Son was blessed in bearing him, but still
    more blessed in keeping your word: Grant us who honor
    the exaltation of her lowliness to follow the example
    of her devotion to your will; through Jesus Christ our
    Lord, who lives and reigns with you and the Holy Spirit,
    one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0915":
  name: Catherine of Genoa
  rank: OPTIONAL
  collect: >
    Gracious God, reveal to your church the depths of your
    love; that, like your servant Catherine of Genoa, we
    might give ourselves in loving service, knowing that we
    have been perfectly loved by you; through Jesus Christ
    our Lord. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0923":
  name: Thecla of Iconium
  rank: OPTIONAL
  collect: >
    God of liberating power, who called Thecla to proclaim
    the gospel and did not permit any obstacle or peril to
    inhibit her: Empower courageous evangelists among
    us, that men and women everywhere may know the
    freedom that you offer us in Jesus Christ, who lives and
    reigns with you and the Holy Spirit, one God, for ever
    and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0924":
  name: Anna Ellison Butler Alexander
  rank: OPTIONAL
  collect: >
    Loving God, who called Anna Alexander as a deaconess
    in your church: Grant us the wisdom to teach the
    gospel of Christ to whomever we meet, by word and by
    example, that all may come to the enlightenment that
    you intend for your people; through Jesus Christ, our
    Teacher and Savior. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0927":
  name: Euphrosyne/Smaragdus of Alexandria
  rank: OPTIONAL
  collect: >
    Merciful God, who looks not with outward eyes but
    discerns the heart of each: we confess that those whom
    we love the most are often strangers to us. Give to all
    parents and children, we pray, the grace to see one
    another as they truly are and as you have called them to
    be. All this we ask in the name of Jesus Christ, our only
    mediator and advocate. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0928":
  name: Paula and Eustochium of Rome
  rank: OPTIONAL
  collect: >
    Compel us, O God, to attend diligently to your Word,
    as did your faithful servants Paula and Eustochium;
    that, by the inspiration of the Holy Spirit, we may find
    it profitable for doctrine, for reproof, for correction, and
    for instruction in righteousness; and that thereby we
    may be made wise unto salvation through faith in Christ
    Jesus our Lord. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1002":
  name: Remigius of Rheims
  rank: OPTIONAL
  collect: >
    Almighty God, who by your servant Remigius spread
    the truth of the gospel and the fullness of the catholic
    faith: Grant that we who glory in the name of Christian
    may show forth our faith in worthy deeds; through
    Jesus Christ our Lord, who lives and reigns with you
    and the Holy Spirit, one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1003":
  name: John Raleigh Mott
  rank: OPTIONAL
  collect: >
    Everlasting God, who leads your people's feet into the
    ways of peace; Raise up heralds and evangelists of your
    kingdom like your servant John Mott, that your church
    may make known to all the world the unsearchable
    riches and unsurpassed peace of your Son, Jesus Christ
    our Lord; to whom with you and the Holy Spirit be all
    honor and glory, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1007":
  name: Birgitta of Sweden
  rank: OPTIONAL
  collect: >
    O God, who beholds all things and whose judgment is
    always mercy; by the example of your servant Birgitta
    of Sweden, give to us in this life the vision of your
    kingdom, where Jesus Christ is all and in all, that we
    may pattern our earthly lives on things heavenly, where
    our lives are hidden with Christ in you; who with him
    and the Holy Spirit live and reign for ever and ever.
    Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1012":
  name: Edith Cavell
  rank: OPTIONAL
  collect: >
    Living God, the source of all healing and wholeness:
    we bless you for the compassionate witness of your
    servant Edith Cavell. Inspire us to be agents of peace
    and reconciliation in a world beset by injustice, poverty,
    and war. We ask this through Jesus Christ, the Prince
    of Peace, who lives and reigns with you and the Holy
    Spirit, one God, to the ages of ages. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1025":
  name: Tabitha (Dorcas) of Joppa
  rank: OPTIONAL
  collect: >
    Most Holy God, who did raise from the dead your
    servant Tabitha to display your power and confirm that
    your Son is Lord; Grant unto us your grace, that, aided
    by her prayers and example, we may be given a new life
    in you, to do works pleasing in your sight; through Jesus
    Christ your Son our Lord; who lives and reigns with
    you, in the unity of the Holy Spirit, one God, for ever
    and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1030":
  name: Maryam of Qidun
  rank: OPTIONAL
  collect: >
    O God of holiness and strength, rescue us from the sins
    that ensnare us and destroy the evils that defame us,
    that, like your servant Maryam of Qidun, we may find
    our own selves inseparable from your love made known
    in Christ Jesus our Lord; who with you and the Holy
    Spirit lives and reigns, one God, in glory everlasting.
    Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1108":
  name: Ammonius
  rank: OPTIONAL
  collect: >
    Drive far from your church, O God, every vain spirit of
    clerical ambition, that, like your servant Ammonius, we
    may refuse to conflate ordination and leadership, and
    may never confuse rank with holiness; in the name of
    your son Jesus Christ our Lord, who alone is our great
    High Priest. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1109":
  name: Richard Rolle, Walter Hilton, and Margery Kempe
  rank: OPTIONAL
  collect: >
    Direct our hearts, O Gracious God, and inspire our
    minds; that like your servants Richard Rolle, Walter
    Hilton, and Margery Kempe, we might pass through the
    cloud of unknowing until we behold your glory face to
    face; in the Name of Jesus Christ our Lord; who with
    you and the Holy Spirit lives and reigns, one God, for
    ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1115":
  name: Herman of Alaska
  rank: OPTIONAL
  collect: >
    Almighty God, who raised up your servant Herman to
    be a light in the world, and to preach the Gospel to the
    people of Alaska: Illuminate our hearts, that we also in
    our own generation may show forth your praise, who
    called us out of darkness and into your marvelous light;
    through Jesus Christ our Lord, who lives and reigns
    with you and the Holy Spirit, one God, now and for
    ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1121":
  name: Mechthilde of Hackeborn and Gertrude the Great
  rank: OPTIONAL
  collect: >
    Almighty God, who gave to your servants Mechthilde
    and Gertrude special gifts of grace to understand and
    teach the truth in Christ Jesus: Grant that by their
    teachings we may know you, the one true God, and
    Jesus Christ your Son; who lives and reigns with you
    and the Holy Spirit, one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1124":
  name: Catherine of Alexandria, Barbara of Nicomedia, and Margaret of Antioch
  rank: OPTIONAL
  collect: >
    Embolden your church, O God, with the stories of your
    saints Catherine, Barbara, and Margaret, that we might
    face all trials and adversities with a fearless mind and
    an unbroken spirit, knowing that we are more than
    conquerors through Jesus Christ who strengthens us.
    Through the same Jesus Christ our Lord. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1203":
  name: Francis Xavier
  rank: OPTIONAL
  collect: >
    God of all nations; Raise up in this and every land,
    evangelists and heralds of your kingdom, that like
    your servant Francis Xavier we may proclaim the
    unsearchable riches of our Savior Jesus Christ; who lives
    and reigns with you and the Holy Spirit, one God, now
    and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1208":
  name: Nicholas Ferrar
  rank: OPTIONAL
  collect: >
    Lord God, make us worthy of your perfect love; that,
    with your deacon Nicholas Ferrar and his household, we
    may rule ourselves according to your Word, and serve
    you with our whole heart; through Jesus Christ our
    Lord, who lives and reigns with you and the Holy Spirit,
    one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1211":
  name: Frederick Howden, Jr.
  rank: OPTIONAL
  collect: >
    Almighty God, our sure defense: We give you thanks for
    your servant[s] Frederick Howden, [N.,] and all military
    chaplains who provided comfort and inspiration in time
    of battle; and, following the example of Jesus the Good
    Shepherd, laid down their lives in the service of others.
    Inspire and strengthen us, also, for the duties of life still
    before us, that we may be faithful to the end; through
    the same Jesus Christ, our Savior and Lord. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1212":
  name: Francis de Sales
  rank: OPTIONAL
  collect: >
    Most gracious God, who has bidden us to act justly, love
    mercy, and walk humbly before you; Grant that we, like
    your servants Francis and Jane, may see and serve Christ
    in all people, and know him as the giver of all good
    things; through the same Jesus Christ our Lord, who
    lives and reigns with you and the Holy Spirit, one God,
    now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1213":
  name: Lucy of Syracuse
  rank: OPTIONAL
  collect: >
    Loving God, for the salvation of all you gave Jesus
    Christ as light to a world in darkness: Illumine us, as
    you did your daughter Lucy, with the light of Christ,
    that by the merits of his passion, we may be led to
    eternal life; through the same Jesus Christ, who with
    you and the Holy Spirit lives and reigns, one God, for
    ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1214":
  name: John of the Cross
  rank: OPTIONAL
  collect: >
    Judge eternal, throned in splendor, who gave John of
    the Cross strength of purpose and faith that sustained
    him even through the dark night of the soul: Shed your
    light on all who love you, in unity with Jesus Christ
    our Savior; who with you and the Holy Spirit lives and
    reigns, one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1215":
  name: Nino of Georgia
  rank: OPTIONAL
  collect: >
    Almighty God, who called your servant Nino to be
    your apostle to the people of Georgia, to bring those
    wandering in darkness to the true light and knowledge
    of you; Grant us so to walk in that light, that we may
    come at last to the light of your everlasting day; through
    Jesus Christ our Lord, who lives and reigns with you
    and the Holy Spirit, one God, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1217":
  name: Dorothy L. Sayers
  rank: OPTIONAL
  collect: >
    Almighty God, who strengthened your servant Dorothy
    Sayers with eloquence to defend Christian teaching:
    Keep us, we pray, steadfast in your true religion, that
    in constancy and peace we may always teach right
    doctrine, and teach doctrine rightly; through Jesus
    Christ our Lord, who lives and reigns with you and the
    Holy Spirit, one God, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1220":
  name: Katharina von Bora
  rank: OPTIONAL
  collect: >
    Almighty God, who called your servant Katharina von
    Bora from a cloister to work for the reform of your
    church: Grant that, for the sake of your glory and the
    welfare of your church, we may go wherever you should
    call, and serve however you should will; through Jesus
    Christ, our only mediator and advocate. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1231":
  name: Frances Joseph Gaudet
  rank: OPTIONAL
  collect: >
    Merciful God, who raised up thy servant Frances Joseph
    Gaudet to be a champion of the oppressed: Grant that
    we, encouraged by her example, may advocate for all
    who are denied the fullness of life to which you have
    called all your children; through Jesus Christ our Lord,
    who lives and reigns with you and the Holy Spirit, one
    God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""
