"0108":
  name: Harriet Bedell
  rank: OPTIONAL
  collect: >
    Holy God, fill us with compassion and respect for
    all people, and empower us for the work of ministry
    whether near or far away; that like your servant Harriet
    Bedell, we may show forth your praise, not only with
    our lips, but in our lives, and by giving up ourselves to
    your service. Through Jesus Christ our Lord, who lives
    and reigns with you and the Holy Spirit, one God, for
    ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0109":
  name: Julia Chester Emery
  rank: OPTIONAL
  collect: >
    God of all creation, who calls us to make disciples of
    all nations and to proclaim your mercy and love: Grant
    that we, after the example of your servant Julia Chester
    Emery, might have vision and courage in proclaiming
    the Gospel to the ends of the earth; through Jesus
    Christ, our light and our salvation, who lives and reigns
    with you and the Holy Spirit, one God, for ever and
    ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0110":
  name: William Laud
  rank: OPTIONAL
  collect: >
    Keep us, O Lord, constant in faith and zealous in
    witness; that, like your servant William Laud, we may
    live in your fear, die in your favor, and rest in your
    peace; for the sake of Jesus Christ your Son our Lord,
    who lives and reigns with you and the Holy Spirit, one
    God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0112":
  name: Aelred of Rievaulx
  rank: OPTIONAL
  collect: >
    Grant to your people, Almighty God, a spirit of mutual
    affection; that, following the example of your servant
    Aelred of Rivaulx, we might know the love of Christ in
    loving one another; through the same Jesus Christ our
    Lord, who lives and reigns with you and the Holy Spirit,
    one God, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0113":
  name: Hilary of Poitiers
  rank: OPTIONAL
  collect: >
    Keep us steadfast, Lord God, in that true faith that we
    professed at our baptism; that, like your servant Hilary
    of Poitiers, we may rejoice in having you for our Father,
    and may abide in your Son, in the fellowship of the Holy
    Spirit; for you live and reign for ever and ever as one
    God in Trinity of Persons. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0117":
  name: Antony of Egypt
  rank: OPTIONAL
  collect: >
    O God, as you by your Holy Spirit enabled your servant
    Antony to withstand the temptations of the world, the
    esh, and the devil; so give us grace to follow you with
    pure hearts and minds, through Jesus Christ our Lord,
    who lives and reigns with you and the Holy Spirit, one
    God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0119":
  name: Wulfstan of Worcester
  rank: OPTIONAL
  collect: >
    Almighty God, whose only-begotten Son led captivity
    captive and gave gifts to your people: Multiply among
    us faithful pastors, who, like your holy bishop Wulfstan,
    will give courage to those who are oppressed and held
    in bondage; and bring us all, we pray, into the true
    freedom of your kingdom; through Jesus Christ our
    Lord, who lives and reigns with you and the Holy Spirit,
    one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0120":
  name: Fabian
  rank: OPTIONAL
  collect: >
    Grant, Almighty God, that in all times of trial and
    persecution, we might remain steadfast in faith and
    endurance, according to the example of your servant
    Fabian, who was faithful even unto death. We ask this
    for the sake of him who laid down his life for us all,
    Jesus Christ our Savior; who lives and reigns with you
    and the Holy Spirit, one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0121":
  name: Agnes and Cecilia of Rome
  rank: OPTIONAL
  collect: >
    Almighty and everlasting God, who chooses those
    whom the world deems powerless to put the powerful
    to shame: Grant us so to cherish the memory of your
    youthful martyrs Agnes and Cecilia, that we might
    share their pure and steadfast faith in you; through Jesus
    Christ our Lord, who lives and reigns with you and the
    Holy Spirit, one God for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0122":
  name: Vincent of Saragossa
  rank: OPTIONAL
  collect: >
    Almighty God, whose deacon Vincent, upheld by
    you, was neither terrified by threats nor overcome by
    torments: Strengthen us to endure all adversity with
    invincible and steadfast faith; through Jesus Christ our
    Lord, who lives and reigns with you and the Holy Spirit,
    one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0123":
  name: Phillips Brooks
  rank: OPTIONAL
  collect: >
    Everlasting God, who implants your living Word in
    the minds and on the lips of all who proclaim your
    truth: Grant that we, like your pastor and preacher
    Phillips Brooks, might proclaim your Gospel in our own
    generation with grace and power. Through Jesus Christ
    our Lord, who lives and reigns with you and the Holy
    Spirit, ever one God, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0124":
  name: Florence Li Tim-Oi
  rank: OPTIONAL
  collect: >
    Almighty God, who pours out your Spirit upon your
    sons and daughters: Grant that we, following the
    example of your servant Florence Li Tim-Oi, chosen
    priest in your church, may with faithfulness, patience,
    and tenacity proclaim your holy gospel to all the
    nations, through Jesus Christ our Lord, who lives and
    reigns with you and the Holy Spirit, one God, in glory
    everlasting. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0126":
  name: Timothy and Titus Companions of Saint Paul
  rank: OPTIONAL
  collect: >
    Almighty God, who called Timothy and Titus to be
    evangelists and teachers, and made them strong to
    endure hardship: Strengthen us to stand fast in adversity,
    and to live godly and righteous lives in this present time,
    that with sure confidence we may look for our blessed
    hope, the glorious appearing of our great God and
    Savior Jesus Christ; who lives and reigns with you and
    the Holy Spirit, one God, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0127":
  name: John Chrysostom
  rank: OPTIONAL
  collect: >
    O God, who gave your servant John Chrysostom
    grace eloquently to proclaim your righteousness in the
    great congregation, and fearlessly to bear reproach for
    the honor of your Name: Mercifully grant to all who
    proclaim your word such excellence in preaching, that
    all your people may be made partakers of the glory that
    shall be revealed; through Jesus Christ our Lord, who
    lives and reigns with you and the Holy Spirit, one God
    for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0128":
  name: Thomas Aquinas
  rank: OPTIONAL
  collect: >
    Almighty God, who has enriched your church with the
    singular learning and holiness of your servant Thomas
    Aquinas: Enlighten us more and more, we pray, by the
    disciplined thinking and teaching of Christian scholars,
    and deepen our devotion by the example of saintly lives;
    through Jesus Christ our Lord, who lives and reigns
    with you and the Holy Spirit, one God, for ever and
    ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0201":
  name: Brigid of Kildare
  rank: OPTIONAL
  collect: >
    O God, whose servant Brigid, kindled with the ame
    of your love, became a shining light in your church:
    Grant that we also may be aame with the spirit of love
    and discipline, and walk before you as children of light;
    through Jesus Christ our Lord, who lives and reigns
    with you, in the unity of the Holy Spirit, one God, now
    and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0203":
  name: Anskar
  rank: OPTIONAL
  collect: >
    Keep your church from discouragement in the day of
    small things, O God, in the knowledge that when you
    have begun a good work, you will bring it to a fruitful
    conclusion, just as you did for your servant Anskar;
    through Jesus Christ our Lord, who lives and reigns
    with you and the Holy Spirit, one God, for ever and
    ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0204":
  name: Manche Masemola
  rank: OPTIONAL
  collect: >
    Almighty and Everlasting God, who kindled the ame
    of your love in the heart of your faithful martyr Manche
    Masemola: Grant to us your servants, a like faith and
    power of love, that we who rejoice in her triumph may
    profit by her example; through Jesus Christ our Lord,
    who lives and reigns with you and the Holy Spirit, one
    God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0205":
  name: Agatha of Sicily
  rank: OPTIONAL
  collect: >
    Almighty and everlasting God, who strengthened your
    martyr Agatha with constancy and courage: Grant us
    for the love of you to make no peace with oppression,
    to fear no adversity, and to have no tolerance for those
    who would use their power to abuse or exploit; Through
    Jesus Christ our Lord, to whom with you and the Holy
    Spirit be all honor and glory, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0213":
  name: Absalom Jones
  rank: OPTIONAL
  collect: >
    Set us free, heavenly Father, from every bond of
    prejudice and fear; that, honoring the steadfast courage
    of your servant Absalom Jones, we may show forth in
    our lives the reconciling love and true freedom of the
    children of God, which you have given us in your Son
    our Savior Jesus Christ; who lives and reigns with you
    and the Holy Spirit, one God, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0214":
  name: Cyril and Methodius
  rank: OPTIONAL
  collect: >
    Almighty and everlasting God, who by the power of the
    Holy Spirit moved your servants Cyril and Methodius
    to bring the light of the Gospel to a hostile and divided
    people: Overcome all bitterness and strife among us by
    the love of Christ, and make us one united family under
    the banner of the Prince of Peace; who lives and reigns
    with you and the Holy Spirit, one God, now and for
    ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0215":
  name: Thomas Bray
  rank: OPTIONAL
  collect: >
    O God of compassion, who opened the heart of your
    servant Thomas Bray to answer the needs of the church
    in the New World: Make your church diligent at all
    times to propagate the Gospel, and to promote the
    spread of Christian knowledge; through Jesus Christ our
    Lord, who lives and reigns with you and the Holy Spirit,
    one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0217":
  name: Janani Luwum
  rank: OPTIONAL
  collect: >
    O God, whose Son the Good Shepherd laid down his
    life for his sheep: We give you thanks for your faithful
    shepherd, Janani Luwum, who after his Savior’s
    example gave up his life for the sake of his ock. Grant
    us to be so inspired by his witness that we make no
    peace with oppression, but live as those who are sealed
    with the cross of Christ, who died and rose again, and
    now lives and reigns with you and the Holy Spirit, one
    God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0218":
  name: Martin Luther
  rank: OPTIONAL
  collect: >
    O God, our refuge and our strength, who raised up your
    servant Martin Luther to reform and renew your church
    in the light of your word: Defend and purify the church
    in our own day and grant that, through faith, we may
    boldly proclaim the riches of your grace, which you have
    made known in Jesus Christ our Savior, who with you
    and the Holy Spirit, lives and reigns, one God, now and
    for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0223":
  name: Polycarp of Smyrna
  rank: OPTIONAL
  collect: >
    O God, the maker of heaven and earth, you gave your
    venerable servant, the holy and gentle Polycarp, the
    boldness to confess Jesus Christ as King and Savior
    and the steadfastness to die for his faith: Give us grace,
    following his example, to share the cup of Christ and to
    rise to eternal life; through Jesus Christ our Lord, who
    lives and reigns with you and the Holy Spirit, one God,
    now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0227":
  name: George Herbert
  rank: OPTIONAL
  collect: >
    Almighty God, who called your servant George Herbert
    from the pursuit of worldly honors to be a poet and
    a pastor of souls: Give us grace, we pray, joyfully to
    dedicate all our powers to your service; through Jesus
    Christ our Lord, who lives and reigns with you and the
    Holy Spirit, one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0228":
  name: Anna Julia Haywood Cooper
  rank: OPTIONAL
  collect: >
    Almighty God, who inspired your servant Anna Julia
    Haywood Cooper with the love of learning and the skill
    of teaching: Enlighten us more and more through the
    discipline of learning, and deepen our commitment to
    the education of all your children; through Jesus Christ
    our Lord, who lives and reigns with you and the Holy
    Spirit, one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0502":
  name: Athanasius of Alexandria
  rank: OPTIONAL
  collect: >
    O Lord, who established your servant Athanasius,
    through wisdom, in your truth: Grant that we,
    perceiving the humanity and divinity of your Son Jesus
    Christ, may follow in his footsteps and ascend the way
    to eternal life, who lives and reigns with you and the
    Holy Spirit, one God, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0504":
  name: Monica
  rank: OPTIONAL
  collect: >
    Deepen our devotion, O Lord, and use us in accordance
    with your will; that inspired by the example of your
    servant Monica, we may bring others to acknowledge
    Jesus Christ as Savior and Lord; who with you and the
    Holy Spirit lives and reigns, one God, for ever and ever.
    Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0508":
  name: Julian of Norwich
  rank: OPTIONAL
  collect: >
    Triune God, Father and Mother to us all, who showed
    your servant Julian revelations of your nurturing and
    sustaining love: Move our hearts, like hers, to seek you
    above all things, for in giving us yourself you give us all.
    Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0509":
  name: Gregory of Nazianzus
  rank: OPTIONAL
  collect: >
    Almighty God, who has revealed to your Church your
    eternal Being of glorious majesty and perfect love as
    one God in Trinity of Persons: Give us grace that, like
    your bishop Gregory of Nazianzus, we may continue
    steadfast in the confession of this faith, and constant in
    our worship of you, Father, Son, and Holy Spirit; who
    live and reign for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0519":
  name: Dunstan
  rank: OPTIONAL
  collect: >
    Direct your Church, O Lord, into the beauty of holiness,
    that, following the good example of your servant
    Dunstan, we may honor your Son Jesus Christ with our
    lips and in our lives; to the glory of his Name, who lives
    and reigns with you and the Holy Spirit, one God, now
    and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0520":
  name: Alcuin of York
  rank: OPTIONAL
  collect: >
    Almighty God, who raised up your servant Alcuin as a
    beacon of learning: Shine in our hearts, we pray, that we
    may also show forth your praise in our own generation,
    for you have called us out of darkness and into your
    marvelous light; through Jesus Christ our Lord, who
    lives and reigns with you and the Holy Spirit, one God,
    now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0524":
  name: Jackson Kemper
  rank: OPTIONAL
  collect: >
    O God, who sent your son Jesus Christ to preach peace
    to those who are far off and to those who are near:
    Grant that we, like your servant Jackson Kemper, may
    proclaim the Gospel in our own day, with courage,
    vision, and perseverance; through the same Jesus Christ
    our Lord,who with you and the Holy Spirit lives and
    reigns, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0525":
  name: Bede
  rank: OPTIONAL
  collect: >
    Almighty God, who has enriched your church with the
    learning and holiness of your servant Bede: Grant us
    to find in Scripture and disciplined prayer the image of
    your Son our Savior Jesus Christ, and to fashion our
    lives according to his likeness, to the glory of your great
    Name and to the benefit of your holy church; through
    the same Jesus Christ our Lord. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0526":
  name: Augustine
  rank: OPTIONAL
  collect: >
    O Lord our God, who by your Son Jesus Christ called
    your servant Augustine to preach the Gospel to the
    English people: We pray that all whom you call and send
    may do your will, bide your time, and see your glory;
    through the same Jesus Christ our Lord, who lives and
    reigns with you and the Holy Spirit, one God, for ever
    and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0601":
  name: Justin Martyr
  rank: OPTIONAL
  collect: >
    O God, who has given your church wisdom and
    revealed to it deep and secret things: Grant that we,
    like your servant Justin and in union with his prayers,
    may find your Word an abiding refuge all the days of
    our lives; through Jesus Christ our Lord, who with you
    and the Holy Spirit lives and reigns, one God, in glory
    everlasting. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0602":
  name: Blandina and Her Companions
  rank: OPTIONAL
  collect: >
    Almighty God, who gave such courage and endurance
    to Blandina and her companions that by their deaths
    many hearts were turned to you; Grant that we, in
    accordance with their example, may also gladly endure
    all that is required of us as we witness to you in our
    own day; through Jesus Christ our Lord, who lives and
    reigns with you and the Holy Spirit, one God, now and
    for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0603":
  name: The Martyrs of Uganda 1886
  rank: OPTIONAL
  collect: >
    O God, by whose providence the blood of the martyrs
    is the seed of the church: Grant that we who remember
    before you the blessed martyrs of Uganda, may, like
    them, be steadfast in our faith in Jesus Christ, to whom
    they gave obedience even to death, and by their sacrifice
    brought forth a plentiful harvest; through Jesus Christ
    our Lord, who lives and reigns with you and the Holy
    Spirit, one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0605":
  name: Boniface
  rank: OPTIONAL
  collect: >
    Pour out your Holy Spirit, O God, upon your church
    in every land, that like your servant Boniface we might
    proclaim the Gospel to all nations, that your kingdom
    might be enlarged and that your holy Name might be
    glorified in all the world; through Jesus Christ our Lord,
    who lives and reigns with you and the same Spirit, one
    God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0609":
  name: Columba of Iona
  rank: OPTIONAL
  collect: >
    O God, who by the preaching of your servant Columba
    caused the light of the Gospel to shine in Scotland:
    Grant, we pray, that, remembering his life and labors,
    we may follow the example of his zeal and patience;
    through Jesus Christ our Lord, who lives and reigns
    with you and the Holy Spirit, one God, for ever and
    ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0610":
  name: Ephrem of Nisibis
  rank: OPTIONAL
  collect: >
    Pour out upon us, O Lord, that same Spirit by which
    your deacon Ephrem declared the mysteries of faith in
    sacred song; that, with gladdened hearts, we too might
    proclaim the riches of your glory; through Jesus Christ
    our Lord, who lives and reigns with you and the Holy
    Spirit, one God, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0612":
  name: Enmegahbowh
  rank: OPTIONAL
  collect: >
    Almighty God, who led your pilgrim people of old by
    fire and cloud: Grant that the ministers of your church,
    following the example of your servant Enmegahbowh,
    may lead your people with fiery zeal and gentle humility;
    through Jesus Christ, who lives and reigns with you in
    the unity of the Holy Spirit, one God, now and for ever.
    Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0614":
  name: Basil of Caesarea
  rank: OPTIONAL
  collect: >
    Almighty God, who has revealed to your church your
    eternal Being of glorious majesty and perfect love as one
    God in Trinity of Persons: Give us grace that, like your
    bishop Basil of Caesarea, we may continue steadfastly in
    the confession of this faith and remain constant in our
    worship of you, Father, Son, and Holy Spirit; ever one
    God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0615":
  name: Evelyn Underhill
  rank: OPTIONAL
  collect: >
    O God, Origin, Sustainer, and End of all creatures:
    Grant that your church, taught by your servant Evelyn
    Underhill, may continually offer to you all glory and
    thanksgiving, and attain with your saints to the blessed
    hope of everlasting life, which you have promised us
    by our Savior Jesus Christ; who with you and the Holy
    Spirit lives and reigns, one God, now and for ever.
    Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0616":
  name: Joseph Butler
  rank: OPTIONAL
  collect: >
    O God, who raises up scholars for your church in every
    generation; we praise you for the wisdom and insight
    granted to your bishop and theologian Joseph Butler,
    and pray that your church may never be destitute of
    such gifts; through Jesus Christ our Lord, who with you
    and the Holy Spirit lives and reigns, one God, for ever
    and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0618":
  name: Bernard Mizeki
  rank: OPTIONAL
  collect: >
    Almighty and everlasting God, who kindled the ame
    of your love in the heart of your holy martyr Bernard
    Mizeki: Grant unto us your servants a like faith and
    power of love, that we, who rejoice in his triumph, may
    profit by his example; through Jesus Christ our Lord,
    who lives and reigns with you and the Holy Spirit, one
    God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0619":
  name: Adelaide Teague Case
  rank: OPTIONAL
  collect: >
    Almighty and everlasting God, who raises up educators
    and teachers of the faith in every generation of your
    church: Grant that following the example of your
    servant Adelaide Teague Case, we might be bold to
    proclaim the reconciling power of Christ’s love in our
    own generation. Through the same Jesus Christ our
    Lord, who lives and reigns with you and the Holy Spirit,
    one God, in glory everlasting. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0622":
  name: Alban
  rank: OPTIONAL
  collect: >
    Almighty God, by whose grace and power your holy
    martyr Alban triumphed over suffering and was faithful
    even unto death: Grant us, who now remember him in
    thanksgiving, to be so faithful in our witness to you in
    this world that we may receive with him the crown of
    life; through Jesus Christ our Lord, who lives and reigns
    with you and the Holy Spirit, one God, for ever and
    ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0628":
  name: Irenaeus of Lyon
  rank: OPTIONAL
  collect: >
    Almighty God, who strengthened your servant Irenaeus
    to defend thy truth against every blast of vain doctrine:
    Keep us, we pray, steadfast in your true religion, that in
    constancy and peace we may walk in the way that leads
    to eternal life; through Jesus Christ our Lord, who lives
    and reigns with you and the Holy Spirit, one God, now
    and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0711":
  name: Benedict of Nursia
  rank: OPTIONAL
  collect: >
    Gracious God, whose service is perfect freedom and
    in whose commandments there is nothing harsh nor
    burdensome: Grant that we, with your servant Benedict,
    may listen with attentive minds, pray with fervent
    hearts, and serve you with willing hands, so that we
    might live at peace with one another and in obedience
    to your Word, Jesus Christ our Lord, who with you and
    the Holy Spirit lives and reigns, one God, now and for
    ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0717":
  name: William White
  rank: OPTIONAL
  collect: >
    O Lord, who in a time of turmoil and confusion raised
    up your servant William White to lead your church into
    ways of stability and peace; Hear our prayer, and give us
    wise and faithful leaders, that, through their ministry,
    your people may be blessed and your will be done;
    through Jesus Christ our Lord, who lives and reigns
    with you and the Holy Spirit, one God, for ever and
    ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0719":
  name: Macrina of Caesarea
  rank: OPTIONAL
  collect: >
    Merciful God, who called your servant Macrina to
    reveal in her life and teaching the riches of your grace
    and truth: Grant that we, following her example, may
    seek after your wisdom and live according to the way of
    your Son our Savior Jesus Christ; who lives and reigns
    with you and the Holy Spirit, one God, for ever and
    ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0720":
  name: Elizabeth Cady Stanton, Amelia Bloomer, and Sojourner Truth
  rank: OPTIONAL
  collect: >
    O God, whose Spirit guides us into all truth and
    makes us free: Strengthen and sustain us as you did
    your servants Elizabeth, Amelia, and Sojourner. Give
    us vision and courage to stand against oppression and
    injustice and all that works against the glorious liberty
    to which you call all your children; through Jesus Christ
    our Savior, who lives and reigns with you and the Holy
    Spirit, one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0724":
  name: Thomas à Kempis
  rank: OPTIONAL
  collect: >
    Holy Father, you have nourished and strengthened
    your church by the writings of your servant Thomas à
    Kempis: Grant that we may learn from him to know
    what is necessary to be known, to love what is to be
    loved, to praise what highly pleases you, and always
    to seek to know and to follow your will; through Jesus
    Christ our Lord, who lives and reigns with you and the
    Holy Spirit, one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0726":
  name: The Parents of the Blessed Virgin Mary
  rank: OPTIONAL
  collect: >
    Almighty God, heavenly Father, we remember in
    thanksgiving this day the parents of the Blessed Virgin
    Mary; and we pray that we all may be made one in the
    heavenly family of your Son Jesus Christ our Lord; who
    with you and the Holy Spirit lives and reigns, one God,
    for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0727":
  name: William Reed Huntington
  rank: OPTIONAL
  collect: >
    O Lord our God, we thank you for instilling in the
    heart of your servant William Reed Huntington a
    fervent love for your church and its mission in the
    world; and we pray that, with unagging faith in your
    promises, we may make known to all people your
    blessed gift of eternal life; through Jesus Christ our
    Lord, who lives and reigns with you and the Holy Spirit,
    one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0729":
  name: Mary and Martha of Bethany
  rank: OPTIONAL
  collect: >
    O God, heavenly Father, your Son Jesus Christ enjoyed
    rest and refreshment in the home of Mary and Martha
    of Bethany: Give us the will to love you, open our hearts
    to hear you, and strengthen our hands to serve you in
    others for his sake; who lives and reigns with you and
    the Holy Spirit, one God, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0730":
  name: William Wilberforce
  rank: OPTIONAL
  collect: >
    Let your continual mercy, O Lord, kindle in your
    Church the never-failing gift of love; that, following the
    example of your servant William Wilberforce, we may
    have grace to defend the poor, and maintain the cause of
    those who have no helper; for the sake of him who gave
    his life for us, your Son our Savior Jesus Christ, who
    lives and reigns with you and the Holy Spirit, one God,
    now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0731":
  name: Ignatius of Loyola
  rank: OPTIONAL
  collect: >
    Almighty God, who called Ignatius of Loyola to the
    service of your Divine Majesty and to seek you in all
    things; Give us also the grace to labor without counting
    the cost and to seek no reward other than knowing that
    we do your will; through Jesus Christ our Lord, who
    lives and reigns with you and the Holy Spirit, now and
    for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0801":
  name: Joseph of Arimathea
  rank: OPTIONAL
  collect: >
    Merciful God, whose servant Joseph of Arimathea with
    reverence and godly fear prepared the body of our Lord
    and Savior for burial and laid it in his own tomb: Grant
    to us, your faithful people, grace and courage to love
    and serve Jesus with sincere devotion all the days of our
    life; through the same Jesus Christ our Lord, who lives
    and reigns with you and the Holy Spirit, one God, for
    ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0807":
  name: John Mason Neale
  rank: OPTIONAL
  collect: >
    Grant, O God, that in all time of our testing we may
    know your presence and obey your will; that, following
    the example of your servant John Mason Neale, we may
    with integrity and courage accomplish what you give
    us to do, and endure what you give us to bear; through
    Jesus Christ our Lord, who lives and reigns with you
    and the Holy Spirit, one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0808":
  name: Dominic
  rank: OPTIONAL
  collect: >
    Almighty God, grant unto your people a hunger for
    your Word and an urgent longing to share your Gospel;
    that, like your servant Dominic, we might labor to bring
    the whole world to the knowledge and love of you as
    you are revealed in your Son Jesus Christ; who lives and
    reigns with you and the Holy Spirit, one God, for ever
    and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0810":
  name: Laurence of Rome
  rank: OPTIONAL
  collect: >
    Almighty God, by whose grace and power your servant
    Laurence triumphed over suffering and despised death:
    Grant that we may be steadfast in service to the poor
    and outcast, and may share with him in the joys of your
    everlasting kingdom; through Jesus Christ our Lord,
    who lives and reigns with you and the Holy Spirit, one
    God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0811":
  name: Clare of Assisi
  rank: OPTIONAL
  collect: >
    O God, whose blessed Son became poor that we,
    through his poverty, might become rich: Deliver us from
    an inordinate love of this world, that we, inspired by the
    devotion of your servant Clare, might serve you with
    singleness of heart and attain to the riches of the age
    to come; through Jesus Christ our Lord, who lives and
    reigns with you and the Holy Spirit, one God, for ever
    and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0812":
  name: Florence Nightingale
  rank: OPTIONAL
  collect: >
    O God, who gave grace to your servant Florence
    Nightingale to bear your healing love into the shadow
    of death: Grant to all who heal the same virtues of
    patience, mercy, and steadfast love, that your saving
    health may be revealed to all; through Jesus Christ, who
    lives and reigns with you and the Holy Spirit, one God,
    now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0813":
  name: Jeremy Taylor
  rank: OPTIONAL
  collect: >
    O God, whose days are without end, and whose mercies
    cannot be numbered: Make us, like your servant Jeremy
    Taylor, deeply aware of the shortness and uncertainty of
    human life; and let your Holy Spirit lead us in holiness
    and righteousness all our days; through Jesus Christ our
    Lord, who lives and reigns with you and the Holy Spirit,
    one God, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0814":
  name: Jonathan Myrick Daniels
  rank: OPTIONAL
  collect: >
    O God of justice and compassion, who puts down the
    proud and mighty from their place, and lifts up the poor
    and the aficted: We give you thanks for your faithful
    witness Jonathan Myrick Daniels, who, in the midst
    of injustice and violence, risked and gave his life for
    another; and we pray that we, following his example,
    may make no peace with oppression; through Jesus
    Christ our Savior, who lives and reigns with you and the
    Holy Spirit, one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0820":
  name: Bernard of Clairvaux
  rank: OPTIONAL
  collect: >
    O God, by whose grace your servant Bernard of
    Clairvaux, kindled with the ame of your love, became
    a burning and a shining light in your church: Grant
    that we also may be aame with the spirit of love and
    discipline and walk before you as children of light;
    through Jesus Christ our Lord, who lives and reigns
    with you and the Holy Spirit, one God, now and for
    ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0825":
  name: Louis
  rank: OPTIONAL
  collect: >
    O God, you called your servant Louis of France to an
    earthly throne that he might advance your heavenly
    kingdom, and gave him zeal for your church and
    love for your people: Mercifully grant that we who
    commemorate him this day may be fruitful in good
    works and attain to the glorious crown of your saints;
    through Jesus Christ our Lord, who lives and reigns
    with you and the Holy Spirit, one God, for ever and
    ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0827":
  name: Thomas Gallaudet and Henry Winter Syle
  rank: OPTIONAL
  collect: >
    O Loving God, whose will it is that everyone should
    come to you and be saved: We bless your holy Name
    for your servants Thomas Gallaudet and Henry Winter
    Syle, and we pray that you will continually move your
    church to respond in love to the needs of all people;
    through Jesus Christ, who lives and reigns with you and
    the Holy Spirit, one God, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0828":
  name: Augustine of Hippo
  rank: OPTIONAL
  collect: >
    Lord God, the light of the minds that know you, the life
    of the souls that love you, and the strength of the hearts
    that serve you: Help us, following the example of your
    servant, Augustine of Hippo, so to know you that we
    may truly love you, and so to love you that we may fully
    serve you, whose service is perfect freedom; through
    Jesus Christ our Lord, who lives and reigns with you
    and the Holy Spirit, one God, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0831":
  name: Aidan of Lindisfarne
  rank: OPTIONAL
  collect: >
    O loving God, you called your servant Aidan from the
    cloister to re-establish the Christian mission in northern
    England: Grant that we, following his example, may use
    what you have given us for the relief of human need, and
    may persevere in commending the saving Gospel of our
    Redeemer Jesus Christ; who lives and reigns with you
    and the Holy Spirit, one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0901":
  name: David Pendleton Oakerhater
  rank: OPTIONAL
  collect: >
    O God of unsearchable wisdom and mercy; Liberate us
    from bondage to self, and empower us to serve you and
    our neighbors, that like your servant David Oakerhater,
    we might bring those who do not know you to the
    knowledge and love of you; through Jesus Christ, the
    captain of our salvation, who lives and reigns with you
    and the Holy Spirit, one God for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0902":
  name: The Martyrs of New Guinea 1942
  rank: OPTIONAL
  collect: >
    Almighty God, we remember before you this day the
    blessed martyrs of New Guinea, who, following the
    example of their Savior, laid down their lives for their
    friends, and we pray that we who honor their memory
    may imitate their loyalty and faith; through Jesus Christ
    our Lord, who lives and reigns with you and the Holy
    Spirit, one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0904":
  name: Paul Jones
  rank: OPTIONAL
  collect: >
    Merciful God, you sent your beloved Son to preach
    peace to those who are far off and to those who are
    near: Raise up in this and every land witnesses who,
    after the example of your servant Paul Jones, will stand
    firm in proclaiming the Gospel of the Prince of Peace,
    our Savior Jesus Christ, who lives and reigns with you
    and the Holy Spirit, one God, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0909":
  name: 'The Martyrs of Memphis: Constance, Thecla, Ruth, Frances, Charles Parsons, and Louis Schuyler 1878'
  rank: OPTIONAL
  collect: >
    We give you thanks and praise, O God of compassion,
    for the heroic witness of the Martyrs of Memphis, who,
    in a time of plague and pestilence, were steadfast in
    their care for the sick and dying, and loved not their
    own lives, even unto death; Inspire in us a like love and
    commitment to those in need, following the example
    of our Savior Jesus Christ; who with you and the Holy
    Spirit lives and reigns, one God, now and for ever.
    Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0910":
  name: Alexander Crummell
  rank: OPTIONAL
  collect: >
    Almighty and everlasting God, we thank you for your
    servant Alexander Crummell, whom you called to
    preach the gospel to those who were far off and to
    those who were near: Raise up, in this and every land,
    evangelists and heralds of your kingdom, that your
    church may proclaim the unsearchable riches of our
    Savior Jesus Christ; who lives and reigns with you and
    the Holy Spirit, one God, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0912":
  name: John Henry Hobart
  rank: OPTIONAL
  collect: >
    Revive your church, Lord God of hosts, whenever it
    falls into complacency and sloth, by raising up devoted
    leaders like your servant John Henry Hobart; and grant
    that their faith and vigor of mind may awaken your
    people to your message and their mission; through Jesus
    Christ our Lord, who lives and reigns with you and the
    Holy Spirit, one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0913":
  name: Cyprian of Carthage
  rank: OPTIONAL
  collect: >
    Almighty God, who gave to your servant Cyprian
    boldness to confess the Name of our Savior Jesus Christ
    before the rulers of this world and courage to die for
    this faith: Grant that we may always be ready to give a
    reason for the hope that is in us and to suffer gladly for
    the sake of our Lord Jesus Christ; who lives and reigns
    with you and the Holy Spirit, one God, for ever and
    ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0916":
  name: Ninian
  rank: OPTIONAL
  collect: >
    O God, who by the preaching of your blessed servant
    and bishop Ninian caused the light of the Gospel to
    shine in the land of Britain: Grant, we pray, that having
    his life and labors in remembrance we may show our
    thankfulness by following the example of his zeal and
    patience; through Jesus Christ our Lord, who lives and
    reigns with you and the Holy Spirit, one God, for ever
    and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0917":
  name: Hildegard of Bingen
  rank: OPTIONAL
  collect: >
    God of all times and seasons: Give us grace that we,
    after the example of your servant Hildegard, may both
    know and make known the joy and jubilation of being
    part of your creation, and show forth your glory in the
    world; through Jesus Christ our Savior, who lives and
    reigns with you and the Holy Spirit, one God, for ever
    and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0918":
  name: Edward Bouverie Pusey
  rank: OPTIONAL
  collect: >
    Grant, O God, that in all time of our testing we may
    know your presence and obey your will; that, following
    the example of your servant Edward Bouverie Pusey,
    we may with integrity and courage accomplish what
    you give us to do, and endure what you give us to bear;
    through Jesus Christ our Lord, who lives and reigns
    with you and the Holy Spirit, one God, for ever and
    ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0919":
  name: Theodore of Tarsus
  rank: OPTIONAL
  collect: >
    Almighty God, who gave your servant Theodore of
    Tarsus gifts of grace and wisdom to establish unity
    where there had been division and order where there
    had been chaos: Create in your church, by the operation
    of the Holy Spirit, such godly union and concord that it
    may proclaim, both by word and example, the Gospel of
    the Prince of Peace; who lives and reigns with you and
    the Holy Spirit, one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0920":
  name: John Coleridge Patteson
  rank: OPTIONAL
  collect: >
    Almighty God, who called your faithful servant John
    Coleridge Patteson and his companions to witness to
    the gospel, and by their labors and sufferings raised
    up a people for your own possession: Pour out your
    Holy Spirit upon your church in every land, that, by
    the service and sacrifice of many, your holy Name may
    be glorified and your kingdom enlarged; through Jesus
    Christ our Lord, who lives and reigns with you and the
    Holy Spirit, one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0922":
  name: Philander Chase
  rank: OPTIONAL
  collect: >
    Almighty God, whose Son Jesus Christ is the pioneer
    and perfecter of our faith: Grant that like your servant
    Philander Chase, we might have the grace to minister
    in Christ’s name in every place, led by bold witnesses to
    the Gospel of the Prince of Peace, Jesus Christ our Lord,
    who lives and reigns with you and the Holy Spirit, one
    God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0925":
  name: Sergius of Radonezh
  rank: OPTIONAL
  collect: >
    O God, whose blessed Son became poor that we,
    through his poverty, might be rich: Deliver us from an
    inordinate love of this world, that we, inspired by the
    devotion of your servant Sergius, may serve you with
    singleness of heart and attain to the riches of the age
    to come; through Jesus Christ our Lord, who lives and
    reigns with you and the Holy Spirit, one God, for ever
    and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0926":
  name: Lancelot Andrewes
  rank: OPTIONAL
  collect: >
    Perfect in us, Almighty God, whatever is lacking of
    your gifts: of faith, to increase it; of hope, to establish
    it; of love, to kindle it; that like your servant Lancelot
    Andrewes we may live in the life of your grace and
    glory; through Jesus Christ your Son our Lord, who
    lives and reigns with you and the Holy Spirit, one God,
    now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"0930":
  name: Jerome
  rank: OPTIONAL
  collect: >
    O God, who gave us the holy Scriptures as a light to
    shine upon our path: Grant us, after the example of
    your servant Jerome, so to learn of you according to
    your holy Word, that we may find the Light that shines
    more and more to the perfect day; even Jesus Christ our
    Lord, who lives and reigns with you and the Holy Spirit,
    one God, now and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1001":
  name: Thérèse of Lisieux
  rank: OPTIONAL
  collect: >
    Gracious Father, who called your servant Thérèse to
    a life of fervent prayer: Give to us that spirit of prayer
    and zeal for the ministry of the Gospel, that the love of
    Christ may be known throughout all the world; through
    the same Jesus Christ, our Lord. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1004":
  name: Francis of Assisi
  rank: OPTIONAL
  collect: >
    Most high, omnipotent, good Lord, grant your people
    grace to renounce gladly the vanities of this world; that,
    following the way of blessed Francis, we may, for love of
    you, delight in your whole creation with perfectness of
    joy; through Jesus Christ our Lord, who lives and reigns
    with you and the Holy Spirit, one God, for ever and
    ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1006":
  name: William Tyndale
  rank: OPTIONAL
  collect: >
    Reveal to us your saving word, O God, that like your
    servant William Tyndale we might hear its call to
    repentance and new life. Plant in our hearts that same
    consuming passion to bring the scriptures to all people
    in their native tongue, and the strength to endure amidst
    all obstacles; through Jesus Christ our Lord, who lives
    and reigns with you and the Holy Spirit, one God, for
    ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1009":
  name: Robert Grosseteste
  rank: OPTIONAL
  collect: >
    O God, our heavenly Father, who raised up your faithful
    servant Robert Grosseteste to be a bishop and pastor in
    your church and to feed your ock: Give abundantly to
    all pastors the gifts of your Holy Spirit, that they may
    minister in your household as true servants of Christ
    and stewards of your divine mysteries; through Jesus
    Christ our Lord, who lives and reigns with you and the
    Holy Spirit, one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1010":
  name: Vida Dutton Scudder
  rank: OPTIONAL
  collect: >
    Most gracious God, you sent your beloved Son to preach
    peace to those who are far off and to those who are
    near: Raise up in your church witnesses who, after the
    example of your servant Vida Dutton Scudder, stand
    firm in proclaiming the power of the gospel of Jesus
    Christ; who lives and reigns with you and the Holy
    Spirit, one God, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1011":
  name: Philip
  rank: OPTIONAL
  collect: >
    O God, who has made of one blood all the peoples of
    the earth and sent your Son to preach peace to those
    who are far off and to those who are near: Grant that
    we, following the example of your servant Philip, may
    bring your Word to those who seek you, for the glory of
    your Name; through Jesus Christ our Lord, who lives
    and reigns with you in the unity of the Holy Spirit, one
    God, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1014":
  name: Samuel Isaac Joseph Schereschewsky
  rank: OPTIONAL
  collect: >
    O God, who in your providence called Joseph
    Schereschewsky to the ministry of this church and gave
    him the gifts and the perseverance to translate the Holy
    Scriptures: Inspire us, by his example and prayers, to
    commit our talents to your service, confident that you
    uphold those whom you call; through Jesus Christ our
    Lord, who lives and reigns with you and the Holy Spirit,
    one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1015":
  name: Teresa of Avila
  rank: OPTIONAL
  collect: >
    O God, who by your Holy Spirit moved Teresa of
    Avila to manifest to your church the way of perfection:
    Grant us, we pray, to be nourished by her teaching, and
    enkindle within us a keen and unquenchable longing
    for true holiness; through Jesus Christ, the joy of loving
    hearts, who with you and the Holy Spirit lives and
    reigns, one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1016":
  name: Hugh Latimer and Nicholas Ridley
  rank: OPTIONAL
  collect: >
    Keep us, O Lord, constant in faith and zealous in
    witness, that, like your servants Hugh Latimer, Nicholas
    Ridley, and Thomas Cranmer we may live in your fear,
    die in your favor, and rest in your peace; for the sake of
    Jesus Christ, your Son our Lord, who lives and reigns
    with you and the Holy Spirit, one God, now and for
    ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1017":
  name: Ignatius of Antioch
  rank: OPTIONAL
  collect: >
    Almighty God, we praise your Name for your bishop
    and martyr Ignatius of Antioch, who offered himself as
    grain to be ground by the teeth of wild beasts that he
    might present to you the pure bread of sacrifice. Accept,
    we pray, the willing tribute of our lives and give us a
    share in the pure and spotless offering of your Son Jesus
    Christ; who lives and reigns with you and the Holy
    Spirit, one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1019":
  name: Henry Martyn
  rank: OPTIONAL
  collect: >
    O God of the nations, who gave to your servant Henry
    Martyn a longing to share your Gospel with all peoples;
    Inspire the church in our own day with that said desire,
    that we may be eager to commit both life and talents to
    you who gave them; through Jesus Christ our Lord, who
    lives and reigns with you and the Holy Spirit, one God,
    for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1026":
  name: Alfred
  rank: OPTIONAL
  collect: >
    O God, who called your servant Alfred to an earthly
    throne that he might advance your heavenly kingdom
    and gave him zeal for your church and love for your
    people: Grant that we, inspired by his example and
    prayers, may remain steadfast in the work you have
    given us to do for the building up of your reign of love;
    through Jesus Christ our Lord, who lives and reigns
    with you and the Holy Spirit, one God, for ever and
    ever. Amen.
    Lesson and Psalms
    Wisdom 6:1-11
    Psalm 21:1-7
    2 Thessalonians 2:13-17
    Luke 6:43-49
    Preface of Baptism
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1029":
  name: James Hannington
  rank: OPTIONAL
  collect: >
    O God, by whose providence the blood of the martyrs
    is the seed of the church: Grant that we who remember
    before you James Hannington and his companions, may,
    like them, be steadfast in our faith in Jesus Christ, to
    whom they gave obedience even to death, and by their
    sacrifice brought forth a plentiful harvest; through Jesus
    Christ our Lord, who lives and reigns with you and the
    Holy Spirit, one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1102":
  name: All Souls
  rank: OPTIONAL
  collect: >
    O God, the Maker and Redeemer of all believers: Grant
    to the faithful departed the unsearchable benefits of the
    passion of your Son; that on the day of his appearing
    they may be manifested as your children; through Jesus
    Christ our Lord, who lives and reigns with you and the
    Holy Spirit, one God, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1103":
  name: Richard Hooker
  rank: OPTIONAL
  collect: >
    O God of truth and peace, you raised up your servant
    Richard Hooker in a day of bitter controversy to defend
    with sound reasoning and great charity the catholic and
    reformed religion: Grant that we may maintain that
    middle way, not as a compromise for the sake of peace,
    but as a comprehension for the sake of truth; through
    Jesus Christ our Lord, who lives and reigns with you
    and the Holy Spirit, one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1106":
  name: William Temple
  rank: OPTIONAL
  collect: >
    O God of light and love, you illumined your church
    through the witness of your servant William Temple:
    Inspire us, we pray, by his teaching and example, that
    we may rejoice with courage, confidence, and faith in
    the Word made esh, and may be led to establish that
    city which has justice for its foundation and love for its
    law; through Jesus Christ, the light of the world, who
    lives and reigns with you and the Holy Spirit, one God,
    now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1107":
  name: Willibrord
  rank: OPTIONAL
  collect: >
    O Lord our God, you call whom you will and send
    them where you choose: We thank you for sending
    your servant Willibrord to be an apostle to the Low
    Countries, to turn them from the worship of idols
    to serve you, the living God; and we entreat you to
    preserve us from the temptation to exchange the perfect
    freedom of your service for servitude to false gods and
    to idols of our own devising; through Jesus Christ our
    Lord, who lives and reigns with you and the Holy Spirit,
    one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1110":
  name: Leo of Rome
  rank: OPTIONAL
  collect: >
    O Lord our God, grant that your church, following the
    teaching of your servant Leo of Rome, may hold fast
    the great mystery of our redemption and adore the one
    Christ, true God and true Man, neither divided from
    our human nature nor separate from your divine Being;
    through the same Jesus Christ our Lord, who lives and
    reigns with you and the Holy Spirit, one God, now and
    for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1111":
  name: Martin of Tours
  rank: OPTIONAL
  collect: >
    Lord God of hosts, you clothed your servant Martin
    the soldier with the spirit of sacrifice and set him as a
    bishop in your church to be a defender of the catholic
    faith: Give us grace to follow in his holy steps, that, at
    the last, we may be found clothed with righteousness in
    the dwellings of peace; through Jesus Christ our Lord,
    who lives and reigns with you and the Holy Spirit, one
    God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1112":
  name: Charles Simeon
  rank: OPTIONAL
  collect: >
    Loving God, whose unerring wisdom and unbounded
    love order all things: Grant us in all things to see your
    hand; that, following the example and teaching of your
    servant Charles Simeon, we may walk with Christ in
    all simplicity and serve you with a quiet and contented
    mind; through Jesus Christ our Lord, who lives and
    reigns with you and the Holy Spirit, one God, for ever
    and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1114":
  name: The Consecration of Samuel Seabury
  rank: OPTIONAL
  collect: >
    We give you thanks, O Lord our God, for your
    goodness in bestowing upon this church the gift of
    the episcopate; and we pray that, joined together in
    unity with our bishops and nourished by your holy
    sacraments, we may proclaim the Gospel of redemption
    with apostolic zeal; through Jesus Christ our Lord, who
    lives and reigns with you and the Holy Spirit, one God,
    now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1116":
  name: Margaret of Scotland
  rank: OPTIONAL
  collect: >
    O God, who called your servant Margaret to an earthly
    throne that she might advance your heavenly kingdom,
    and gave her zeal for your church and love for your
    people: Mercifully grant that we also may be fruitful in
    good works, and attain to the glorious crown of your
    saints; through Jesus Christ our Lord, who lives and
    reigns with you and the Holy Spirit, one God, for ever
    and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1117":
  name: Hugh of Lincoln
  rank: OPTIONAL
  collect: >
    Holy God, who endowed your servant Hugh of Lincoln
    with wise and cheerful boldness, and taught him to
    commend the discipline of holy life to kings and princes:
    Grant that we also, rejoicing in the Good News of your
    mercy, and fearing nothing but the loss of you, may be
    bold to speak the truth in love, in the name of Jesus
    Christ our Redeemer; who lives and reigns with you and
    the Holy Spirit, one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1118":
  name: Hilda of Whitby
  rank: OPTIONAL
  collect: >
    O God of peace, by whose grace the abbess Hilda was
    endowed with gifts of justice, prudence, and strength to
    rule as a wise mother over the nuns and monks of her
    household: Raise up these gifts in us, that we, following
    her example and prayers, may build up one another in
    love to the benefit of your church; through Jesus Christ
    our Lord, who lives and reigns with you and the Holy
    Spirit, one God, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1119":
  name: Elizabeth of Hungary
  rank: OPTIONAL
  collect: >
    Almighty God, by your grace your servant Elizabeth
    of Hungary recognized and honored Jesus in the poor
    of this world: Grant that we, following her example,
    may with love and gladness serve those in any need or
    trouble, in the name and for the sake of Jesus Christ;
    who lives and reigns with you and the Holy Spirit, one
    God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1120":
  name: Edmund
  rank: OPTIONAL
  collect: >
    Merciful God, who gave grace and fortitude to Edmund
    to die nobly for your Name: Bestow on us your servants
    the shield of faith, with which we can withstand the
    assaults of our ancient enemy; through Jesus Christ our
    Redeemer, who lives and reigns with you and the Holy
    Spirit, one God, now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1122":
  name: Clive Staples Lewis
  rank: OPTIONAL
  collect: >
    O God of searing truth and surpassing beauty, we give
    you thanks for Clive Staples Lewis, whose sanctified
    imagination lit fires of faith in young and old alike;
    Surprise us also with your joy and draw us into that new
    and abundant life which is ours in Christ Jesus, who
    lives and reigns with you and the Holy Spirit, one God,
    now and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1123":
  name: Clement of Rome
  rank: OPTIONAL
  collect: >
    Almighty God, who chose your servant Clement of
    Rome to recall the church in Corinth to obedience and
    stability: Grant that your church may be grounded
    and settled in your truth by the indwelling of the Holy
    Spirit; reveal to it what is not yet known; fill up what is
    lacking; confirm what has already been revealed; and
    keep it blameless in your service; through Jesus Christ
    our Lord, who lives and reigns with you and the Holy
    Spirit, one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1125":
  name: James Otis Sargent Huntington
  rank: OPTIONAL
  collect: >
    Preserve your people, O God, from discouragement
    in the face of adversity, as you did your servant James
    Huntington, knowing that when you have begun a good
    work you will bring it to completion. Through Jesus
    Christ our Lord, who with you and the Holy Spirit lives
    and reigns, one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1128":
  name: Kamehameha and Emma of Hawai‘i
  rank: OPTIONAL
  collect: >
    O God, who called your servants Kamehameha and
    Emma to an earthly throne that they might advance
    your heavenly kingdom, and gave them zeal for your
    church and love for your people: Mercifully grant that
    we also may be fruitful in good works, and attain to the
    glorious crown of your saints; through Jesus Christ our
    Lord, who lives and reigns with you and the Holy Spirit,
    one God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1201":
  name: Charles de Foucauld
  rank: OPTIONAL
  collect: >
    Loving God, help us to know you wherever we find
    you and seek to serve you in all people, that with your
    servant Charles de Foucauld, we may be faithful even
    unto death; through Jesus Christ, who lives and reigns
    with you and the Holy Spirit, one God, now and for
    ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1202":
  name: Channing Moore Williams
  rank: OPTIONAL
  collect: >
    O God, who in your providence called Channing Moore
    Williams to the ministry of this church and gave him the
    gifts and the perseverance to preach the Gospel in new
    lands: Inspire us, by his example and prayers, to commit
    our talents to your service, confident that you uphold
    those whom you call; through Jesus Christ our Lord,
    who lives and reigns with you and the Holy Spirit, one
    God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1204":
  name: John of Damascus
  rank: OPTIONAL
  collect: >
    Confirm our minds, O Lord, in the mysteries of the
    true faith, set forth with power by your servant John
    of Damascus; that we, with him, confessing Jesus to be
    true God and true Man and singing the praises of the
    risen Lord, may, by the power of the resurrection, attain
    to eternal joy; through Jesus Christ our Lord, who lives
    and reigns with you and the Holy Spirit, one God, now
    and for ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1205":
  name: Clement of Alexandria
  rank: OPTIONAL
  collect: >
    O God of unsearchable wisdom, you gave your servant
    Clement grace to understand and teach the truth as it
    is in Jesus Christ, the source of all truth: Grant to your
    church the same grace to discern your Word wherever
    truth is found; through Jesus Christ our unfailing light,
    who lives and reigns with you and the Holy Spirit, one
    God, for ever and ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1206":
  name: Nicholas of Myra
  rank: OPTIONAL
  collect: >
    Grant, Almighty God, that your church may be so
    inspired by the example of your servant Nicholas of
    Myra, that it may never cease to work for the welfare of
    children, the safety of sailors, the relief of the poor, and
    the help of those tossed by tempests of doubt or grief;
    through Jesus Christ our Lord, who lives and reigns
    with you and the Holy Spirit, one God, now and for
    ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1207":
  name: Ambrose of Milan
  rank: OPTIONAL
  collect: >
    O God, who gave your servant Ambrose grace
    eloquently to proclaim your righteousness in the great
    congregation and fearlessly to bear reproach for the
    honor of your Name: Mercifully grant to all bishops and
    pastors such excellence in preaching and faithfulness
    in ministering your Word, that your people may be
    partakers with them of the glory that shall be revealed;
    through Jesus Christ our Lord, who lives and reigns
    with you and the Holy Spirit, one God, now and for
    ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""

"1229":
  name: Thomas Becket
  rank: OPTIONAL
  collect: >
    O God, our strength and our salvation, you called your
    servant Thomas Becket to be a shepherd of your people
    and a defender of your church; Keep your household
    from all evil and raise up faithful pastors and leaders
    who are wise in the ways of the gospel; through Jesus
    Christ, the shepherd of our souls, who lives and reigns
    with you and the Holy Spirit, one God, for ever and
    ever. Amen.
  morning:
    psalter: ""
    readings:
    - ""
    - ""
  evening:
    psalter: ""
    readings:
    - ""
    - ""
